/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package mainPackage;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.ResultSetMetaData;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author Windows8.1
 */
public class updatePanel extends javax.swing.JPanel {

    private final String DATABSE_URL = "jdbc:derby://localhost:1527/libraryDb";
    private final String username = "oracle";
    private final String password = "pass";
    private final String UPDATE_REC = "UPDATE tblbooks SET title = ?,author = ?, genre = ? WHERE id = ?";
    private final String CHECK_REC = "SELECT * FROM TBLBOOKS WHERE ID = ?";

    private Connection connection;
    private PreparedStatement statement;
    private ResultSet resultset;
    private ResultSetMetaData rsMetadata;

    public updatePanel() {
        initComponents();
        try {
            connection = DriverManager.getConnection(DATABSE_URL, username, password);
        } catch (SQLException ex) {
            Logger.getLogger(updatePanel.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    public int checkRecords(int id) {

        int count = 0;

        try {
            statement = connection.prepareStatement(CHECK_REC);
            statement.setInt(1, id);
            resultset = statement.executeQuery();

            while (resultset.next()) {
                count = count + 1;
            }

            if (count == 1) {

                return count;
            }

        } catch (SQLException ex) {
            Logger.getLogger(addPanel.class.getName()).log(Level.SEVERE, null, ex);
        }

        return count = 0;

    }

    public void updateRecord(int id, String title, String author, Object genre) {

        try {

            if (checkRecords(id) == 1) {
                statement = connection.prepareStatement(UPDATE_REC);
                statement.setInt(4, id);
                statement.setString(1, title);
                statement.setString(2, author);
                statement.setObject(3, genre);
                statement.executeUpdate();
                JOptionPane.showMessageDialog(null, "The Book has been Updated!");
                idField.setText("");
                titleField.setText("");
                authorField.setText("");
            } else {
                JOptionPane.showMessageDialog(null, "Book ID not Found!");
                idField.setText("");
                titleField.setText("");
                authorField.setText("");
            }

        } catch (SQLException ex) {
            System.out.println(ex);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        updateButton = new javax.swing.JButton();
        idField = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        titleField = new javax.swing.JTextField();
        authorField = new javax.swing.JTextField();
        genreBox = new javax.swing.JComboBox<>();

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel2.setText("UPDATE");

        jLabel5.setFont(new java.awt.Font("Georgia", 0, 24)); // NOI18N
        jLabel5.setText("Genre:");

        jLabel6.setFont(new java.awt.Font("Georgia", 0, 24)); // NOI18N
        jLabel6.setText("Id:");

        updateButton.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        updateButton.setText("Update");
        updateButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateButtonActionPerformed(evt);
            }
        });

        idField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                idFieldActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Georgia", 0, 24)); // NOI18N
        jLabel1.setText("Author:");

        jLabel3.setFont(new java.awt.Font("Georgia", 0, 24)); // NOI18N
        jLabel3.setText("Title:");

        titleField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                titleFieldActionPerformed(evt);
            }
        });

        genreBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Adventure", "Romance", "Fantasy", "Science fiction", "Satire", "Mystery", "Horror", "Self help", "Health", "Guide", "Travel", "Children's", "Religion & Spirituality", "Science", "History", "Math", "Anthology", "Poetry", "Encyclopedias", "Dictionaries", "Comics", "Art", "Cookbooks", "Diaries", "Journals", "Prayer books", "Series", "Trilogy", "Biographies", "Autobiographies" }));
        genreBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                genreBoxActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addComponent(jLabel2))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(123, 123, 123)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel3)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6))
                        .addGap(93, 93, 93)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(idField)
                                .addComponent(authorField, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(titleField, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(genreBox, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(updateButton)
                .addContainerGap(84, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addComponent(jLabel2)
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel6)
                                .addComponent(idField, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGap(31, 31, 31)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel3)
                                .addComponent(titleField, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGap(30, 30, 30)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(authorField, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel1))
                            .addGap(27, 27, 27)
                            .addComponent(jLabel5))
                        .addComponent(genreBox, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(172, 172, 172)
                        .addComponent(updateButton)))
                .addContainerGap(166, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void updateButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateButtonActionPerformed

        try {

            String id = idField.getText();
            int id1 = Integer.parseInt(id);
            String title = titleField.getText();
            String author = authorField.getText();
            Object genre = "";

            switch (genreBox.getSelectedIndex()) {

                case 0:
                    genre = genreBox.getSelectedItem();
                    System.out.println(genre);
                    break;
                case 1:
                    genre = genreBox.getSelectedItem();
                    break;
                case 2:
                    genre = genreBox.getSelectedItem();
                    break;
                case 3:
                    genre = genreBox.getSelectedItem();
                    break;
                case 4:
                    genre = genreBox.getSelectedItem();
                    break;
                case 5:
                    genre = genreBox.getSelectedItem();
                    break;
                case 6:
                    genre = genreBox.getSelectedItem();
                    break;
                case 7:
                    genre = genreBox.getSelectedItem();
                    break;
                case 8:
                    genre = genreBox.getSelectedItem();
                    break;
                case 9:
                    genre = genreBox.getSelectedItem();
                    break;
                case 10:
                    genre = genreBox.getSelectedItem();
                    break;
                case 11:
                    genre = genreBox.getSelectedItem();
                    break;
                case 12:
                    genre = genreBox.getSelectedItem();
                    break;
                case 13:
                    genre = genreBox.getSelectedItem();
                    break;
                case 14:
                    genre = genreBox.getSelectedItem();
                    break;
                case 15:
                    genre = genreBox.getSelectedItem();
                    break;
                case 16:
                    genre = genreBox.getSelectedItem();
                    break;
                case 17:
                    genre = genreBox.getSelectedItem();
                    break;
                case 18:
                    genre = genreBox.getSelectedItem();
                    break;
                case 19:
                    genre = genreBox.getSelectedItem();
                    break;
                case 20:
                    genre = genreBox.getSelectedItem();
                    break;
                case 21:
                    genre = genreBox.getSelectedItem();
                    break;
                case 22:
                    genre = genreBox.getSelectedItem();
                    break;
                case 23:
                    genre = genreBox.getSelectedItem();
                    break;
                case 24:
                    genre = genreBox.getSelectedItem();
                    break;
                case 25:
                    genre = genreBox.getSelectedItem();
                    break;
                case 26:
                    genre = genreBox.getSelectedItem();
                    break;
                case 27:
                    genre = genreBox.getSelectedItem();
                    break;
                case 28:
                    genre = genreBox.getSelectedItem();
                    break;
                case 29:
                    genre = genreBox.getSelectedItem();
                    break;
                default:
                    genre = "";
                    break;
            }

            if (id.equals("") || title.equals("") || title.equals("") || author.equals("") || genre.equals("")) {

                JOptionPane.showMessageDialog(null, "Please Fill out all the needed areas.");

            } else {
                updateRecord(id1, title, author, genre);
            }
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(null, "Please Input a Proper ID Number.");
        }
    }//GEN-LAST:event_updateButtonActionPerformed

    private void idFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_idFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_idFieldActionPerformed

    private void titleFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_titleFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_titleFieldActionPerformed

    private void genreBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_genreBoxActionPerformed

    }//GEN-LAST:event_genreBoxActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField authorField;
    private javax.swing.JComboBox<String> genreBox;
    private javax.swing.JTextField idField;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JTextField titleField;
    private javax.swing.JButton updateButton;
    // End of variables declaration//GEN-END:variables
}
