/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package mainPackage.admin;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.ResultSetMetaData;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Windows8.1
 */
public class ViewAllAccountsPanel_ADMIN extends javax.swing.JPanel {

    private final String DATABSE_URL = "jdbc:derby://localhost:1527/libraryDb";
    private final String username = "oracle";
    private final String password = "pass";
    private final String GET_RECORDS = "SELECT * FROM ACCOUNTS";

    private Connection connection;
    private PreparedStatement statement;
    private ResultSet resultset;
    private ResultSetMetaData rsMetadata;

    public ViewAllAccountsPanel_ADMIN() {
        initComponents();
        try {
            connection = DriverManager.getConnection(DATABSE_URL, username, password);
        } catch (SQLException ex) {
            Logger.getLogger(ViewAllAccountsPanel_ADMIN.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    public void viewRecords() {
        try {

            statement = connection.prepareStatement(GET_RECORDS);
            resultset = statement.executeQuery();
            rsMetadata = resultset.getMetaData();

            DefaultTableModel dtmPrefix = new DefaultTableModel() {
                @Override
                public boolean isCellEditable(int row, int column) {
                    return false;
                }
            };
            dtmPrefix.addColumn("STUDENT ID");
            dtmPrefix.addColumn("FIRST NAME");
            dtmPrefix.addColumn("LAST NAME");
            dtmPrefix.addColumn("MIDDLE NAME");
            dtmPrefix.addColumn("USERNAME");
            dtmPrefix.addColumn("PASSWORD");
            dtmPrefix.addColumn("BOOK ID");
            dtmPrefix.addColumn("BORROWED");
            dtmPrefix.addColumn("STATUS");

            while (resultset.next()) {

                dtmPrefix.addRow(new Object[]{
                    resultset.getString("STUDENT_NUMBER"),
                    resultset.getString("FIRST_NAME"),
                    resultset.getString("LAST_NAME"),
                    resultset.getString("MIDDLE_NAME"),
                    resultset.getString("USERNAME"),
                    resultset.getString("PASSWORD"),
                    resultset.getString("BOOK_ID"),
                    resultset.getString("DATE_BORROWED"),
                    resultset.getString("ACCT_STATUS")
                });
                displayTable.setModel(dtmPrefix);
            }
        } catch (SQLException ex) {
            Logger.getLogger(ViewAllBooksPanel_ADMIN.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane2 = new javax.swing.JScrollPane();
        displayTable = new javax.swing.JTable();

        addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                panelActivate(evt);
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });

        displayTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        displayTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                doubleClick(evt);
            }
        });
        jScrollPane2.setViewportView(displayTable);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 690, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(53, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void panelActivate(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_panelActivate

        viewRecords();

    }//GEN-LAST:event_panelActivate

    private void doubleClick(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_doubleClick

        int rowTable = displayTable.getSelectedRow();

        Object sNumber = displayTable.getValueAt(rowTable, 0);
        Object fName = displayTable.getValueAt(rowTable, 1);
        Object lName = displayTable.getValueAt(rowTable, 2);
        Object mName = displayTable.getValueAt(rowTable, 3);
        Object username = displayTable.getValueAt(rowTable, 4);
        Object password = displayTable.getValueAt(rowTable, 5);
        Object book_id = displayTable.getValueAt(rowTable, 6);
        Object date_borrowed = displayTable.getValueAt(rowTable, 7);

        if (evt.getClickCount() == 2) {
            JTable target = (JTable) evt.getSource();
            int row = target.getSelectedRow();

            JOptionPane.showMessageDialog(null, "Student Number: " + sNumber + "\n"
                    + "First Name: " + fName + "\n"
                    + "Last Name: " + lName + "\n"
                    + "Middle Name: " + mName + "\n"
                    + "Username: " + username + "\n"
                    + "Password: " + password + "\n"
                    + "Book ID: " + book_id + "\n"
                    + "Date Borrowed: " + date_borrowed + "\n"
            );

        }


    }//GEN-LAST:event_doubleClick


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private static javax.swing.JTable displayTable;
    private javax.swing.JScrollPane jScrollPane2;
    // End of variables declaration//GEN-END:variables
}
